name: Test
on: [push]
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install Yarn Packages
        run: yarn --frozen-lockfile
      - name: TEST 🔧
        run: yarn run lint
